version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_USER: db_user
#      MYSQL_PASSWORD: db_password
    ports: ["3306:3306"]
    volumes:
    - mysql-data-uploader:/var/lib/mysql

volumes:
  mysql-data-uploader: {}
