version: '3'
services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uploader
    ports: ["5432:5432"]
    volumes:
      - postgres-data-uploader:/var/lib/postgresql/data

volumes:
  postgres-data-uploader: {}
